import { Team } from "@/types/team";

const teamData: Team[] = [
  {
    id: 76,
    name: "Tamara Nikolendzic",
    designation: "Founder & CEO",
    image: "/images/team/team-09.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 51,
    name: "Nenad Mikovic",
    designation: "Developer",
    image: "/images/team/team-10.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 86,
    name: "Gilbert Graham",
    designation: "Backend Developer",
    image: "/images/team/team-03.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 1,
    name: "Elijah Carroll",
    designation: "Content Writer",
    image: "/images/team/team-04.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 64,
    name: "Millie Buchanan",
    designation: "SEO Expert",
    image: "/images/team/team-05.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 59,
    name: "Jeffrey Alvarado",
    designation: "DevOps",
    image: "/images/team/team-06.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 39,
    name: "Kathryn Klein",
    designation: "Full-stack Developer",
    image: "/images/team/team-07.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
  {
    id: 87,
    name: "Minnie Jordan",
    designation: "Testing Developer",
    image: "/images/team/team-08.png",
    fbLink: "https://www.facebook.com/",
    twitterLink: "https://twitter.com/",
    instagramLink: "https://www.instagram.com/",
  },
];

export default teamData;
